language: php
php:
  - "7.2"

install:
  - echo "Building up docker containers"
  - docker-compose up -d
  - echo "Done"
  - docker ps
  - docker exec -ti php composer install --no-scripts

script:
  - docker exec -ti php vendor/bin/phpunit tests

after_success:
  - echo "Tests passed"