language: php
php:
  - "7.2"

install:
  - sudo usermod -a -G www-data `whoami`
  - sudo chown -R www-data:www-data /var/www
  - sudo chmod -R 774 /var/www
  - echo "Building up docker containers"
  - make build
  - echo "Initializing project"
  - make deploy

script:
  - make tests

after_success:
  - echo "Tests passed"