language: php
php:
  - "7.2"
services:
  - docker

install:
  - echo "Building up docker containers"
  - make up
  - echo "Initializing project"
  - make deploy

script:
  - make tests

after_success:
  - echo "Tests passed"