language: php
sudo: false
php:
  - "7.2"
services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache

install:
  - echo "Building up docker containers"
  - make up
  - echo "Initializing project"
  - make deploy

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make tests; fi'

deploy:
  - provider: script
    script: bash deploy/production.sh
    on:
      branch: main