language: php
php:
  - "7.2"
services:
  - docker

install:
  - echo "Building up docker containers"
  - make up
  - echo "Initializing project"
  - make deploy

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make tests; fi'

deploy:
  - provider: script
    script: deploy/production.sh
    on:
      branch: main