language: php
php:
  - "7.2"
services:
  - docker

jobs:
  include:
    - stage: Build Environment
      script:
        - make up
    - stage: Deploy project
      script: make deploy
    - stage: Test
      script: make tests