language: php
php:
  - "7.2"

install:
  - echo "Building up docker containers"
  - make build
  - echo "Initializing project"
  - make deploy

script:
  - make tests

after_success:
  - echo "Tests passed"