version: '3'
services:
  mysql:
    image: mysql:5.7.17
    container_name: travis-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=zingle
      - MYSQL_DATABASE=zingle
    volumes:
      - ./docker/volumes/db.mysql:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: travis-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - default

  php:
    build:
      context: ./docker/php/
    container_name: travis-php
    volumes:
      - ./:/var/www
    networks:
      - default

networks:
  default: